version: 2.1
orbs:
  node: circleci/node@4.7.0

workflows:
  build_each_env:
    jobs: # https://nodejs.org/ja/about/releases/
      - build:
          name: Node.js 14
          node_ver: "14.19" # EOL: 2023-04-30 (LTS)
      - build:
          name: Node.js 16
          node_ver: lts # EOL: 2024-04-30 (LTS)

jobs:
  build:
    parameters:
      node_ver:
        type: string
        default: lts
    docker:
      - image: cimg/node:<< parameters.node_ver >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup & Test
          command: npm cit
      - run:
          name: Setup & Test for Example
          command: npm cit
          working_directory: ./example
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
